DROP TABLE IF EXISTS apps, hits CASCADE;

CREATE TABLE IF NOT EXISTS apps (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS hits (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app_id BIGINT REFERENCES apps(id) ON DELETE CASCADE,
    uri VARCHAR(512) NOT NULL,
    ip VARCHAR(15) NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE
);